### ISSUE TITLE
vpdupdate failing

### ISSUE THREAD

**Issue by bssrikanth** [open-power-host-os/libvpd#1]
[root@ltc-boston128 ~]# /usr/sbin/vpdupdate
terminate called after throwing an instance of 'std::ios_base::failure'
  what():  basic_filebuf::underflow error reading the file
Aborted
[root@ltc-boston128 ~]# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (AltArch) 
[root@ltc-boston128 ~]# uname -r
4.13.0-4.rel.git49564cb.el7.centos.ppc64le

<cde:info> Mirrored with LTC bug #159382 </cde:info>

**Comment by bssrikanth** [comment]
[root@ltc-boston128 ~]# rpm -qa | grep -i vpd
lsvpd-1.7.8-2.rel.gitb5542ab.el7.centos.ppc64le
libvpd-2.2.5-7.rel.git767b629.el7.centos.ppc64le

**Comment by hegdevasant** [comment]
Below upstream commit should fix this issue .,

commit c36b20b7dc2e787f7285e459851df1a74368e8e3
Author: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>
Date:   Wed Sep 20 16:52:35 2017 +0530

    lsvpd: Add workaround for std::ios_base::failure' issue

I've pushed changes to hostos-stable / release branches.. please rebuild.

-Vasant

**Comment by cdeadmin** [comment]
------- Comment From hegdevasant@in.ibm.com 2017-09-28 02:02:44 EDT-------
(In reply to comment #2)
&gt;
&gt; [root@ltc-boston128 ~]# rpm -qa | grep -i vpd
&gt; lsvpd-1.7.8-2.rel.gitb5542ab.el7.centos.ppc64le
&gt; libvpd-2.2.5-7.rel.git767b629.el7.centos.ppc64le
&gt; Below upstream commit should fix this issue .,
&gt; 
&gt; commit c36b20b7dc2e787f7285e459851df1a74368e8e3
&gt; Author: Vasant Hegde &lt;hegdevasant@linux.vnet.ibm.com&gt;
&gt; Date:   Wed Sep 20 16:52:35 2017 +0530
&gt; 
&gt;     lsvpd: Add workaround for std::ios_base::failure' issue
&gt; 
&gt; I've pushed changes to hostos-stable / release branches.. please rebuild.

I meant for hostos-devel and stable branches.

-Vasant

**Comment by cdeadmin** [comment]
------- Comment From bssrikanth@in.ibm.com 2017-10-09 06:44:21 EDT-------
Verified on:
[root@zzfp365-lp1 ~]# uname -r
4.13.0-4.rel.git49564cb.el7.centos.ppc64le
[root@zzfp365-lp1 ~]# rpm -qa | grep -i libvpd
libvpd-2.2.5-8.rel.git7d959c5.el7.centos.ppc64le
[root@zzfp365-lp1 ~]# vpdupdate
[root@zzfp365-lp1 ~]# lsmcode
Version of System Firmware is FW910.00 (UL910_027) (t) FW910.00 (UL910_027) (p) FW910.00 (UL910_027) (b)

Now vpdupdate works without the reported issue... closing
