### ISSUE TITLE
lsmcode does not return hostboot-binaries version on Boston-LC

### ISSUE THREAD

**Issue by bssrikanth** [open-power-host-os/libvpd#2]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=164228 </cde:info>

On boston-LC:

[root@9 ~]# rpm -qa | grep vpd
libvpd-2.2.5-8.dev.git7d959c5.el7.centos.ppc64le
lsvpd-1.7.8-4.dev.git63c0dfc.el7.centos.ppc64le
[root@9 ~]# uname -r
4.15.0-3.dev.gitd34a158.el7.centos.ppc64le

[root@9 ~]# lsmcode
Version of System Firmware : 
 Product Name          : OpenPOWER Firmware
 Product Version       : open-power-SUPERMICRO-P9DSU-1.02-20180123-imp
 Product Extra         : 	occ-fce2d94
 Product Extra         : 	skiboot-v5.9-238-g43eb8bbcbaa5-p6a690fc
 Product Extra         : 	petitboot-v1.6.6-p47185f6
 Product Extra         : 	sbe-86ae83c
 Product Extra         : 	machine-xml-d0ebc02
 Product Extra         : 	hostboot-52ca812
 Product Extra         : 	linux-4.14.13-openpower1-p2554bd9

On witherspoon:
[root@ltc-wspoon5 ~]# rpm -qa | grep vpd
libvpd-2.2.5-8.dev.git7d959c5.el7.centos.ppc64le
lsvpd-1.7.8-4.dev.git63c0dfc.el7.centos.ppc64le
[root@ltc-wspoon5 ~]# uname -r
4.15.0-3.dev.gitd34a158.el7.centos.ppc64le
[root@ltc-wspoon5 ~]# 

[root@ltc-wspoon5 ~]# lsmcode
Version of System Firmware : 
 Product Name          : OpenPOWER Firmware
 Product Extra         : 	occ-39d5490
 Product Extra         : 	skiboot-v5.9.8
 Product Extra         : 	buildroot-2017.08-8-g5e23247
 Product Extra         : 	capp-ucode-p9-dd2-v2
 Product Extra         : 	petitboot-v1.6.3-p9911320
 Product Extra         : 	sbe-b6b7bb7
 Product Extra         : 	hostboot-binaries-159f2e8
 Product Extra         : 	machine-xml-592a6dd
 Product Extra         : 	hostboot-7050d0a
 Product Extra         : 	linux-4.13.16-openpower1-p98dd271

Issue: hostboot-binaries version is missing from lsmcode o/p on boston-LC.

**Comment by cdeadmin** [comment]
------- Comment (attachment only) From bssrikanth@in.ibm.com 2018-02-03 04:26:40 EDT-------

**Comment by cdeadmin** [comment]
------- Comment From hegdevasant@in.ibm.com 2018-02-08 08:03:28 EDT-------
User space tools depends on device tree to get these information.

OPAL depends on VERSION partition in PNOR to get these information.

Looks like this is not populated by SMC in VERSION section of PNOR. Please open github issue against  SMC if you really need this information.

Nothing can be done from OPAL or user space tools.

-Vasant

**Comment by bssrikanth** [comment]
Ok.
